# Copyright (c) Microsoft Corporation. All rights reserved.
"""Diagram generation and example functions for the azure-diagram-mcp-server."""

import diagrams
import importlib
import inspect
import logging
import os
import re
import signal
import traceback
import uuid
import datetime
from azure_diagram_mcp_server.models import (
    DiagramExampleResponse,
    DiagramGenerateResponse,
    DiagramIconsResponse,
    DiagramType,
)
from azure_diagram_mcp_server.scanner import scan_python_code
from typing import Optional
import platform
import tempfile
import subprocess

# Add Graphviz to PATH if on Windows (cross-platform compatible)
if platform.system() == "Windows":
    # Try common Graphviz installation paths on Windows
    possible_paths = [
        r"C:\Program Files\Graphviz\bin",
        r"C:\Program Files (x86)\Graphviz\bin",
        os.path.expanduser("~\\AppData\\Local\\Packages\\Graphviz*\\LocalCache\\Local\\bin"),
    ]
    for graphviz_path in possible_paths:
        if os.path.exists(graphviz_path) and graphviz_path not in os.environ.get("PATH", ""):
            os.environ["PATH"] += os.pathsep + graphviz_path
            break

logger = logging.getLogger(__name__)

# Azure is imported last so it wins the names it shares with the other providers
# (SQL, Mobile, Firewall, Subnet, Databricks, Users, InputOutput).
_PROVIDER_ORDER = ('generic', 'programming', 'k8s', 'onprem', 'azure')


def _build_base_namespace() -> dict:
    """Namespace with every azure/generic/onprem icon pre-imported, so generated code needs no imports."""
    namespace: dict = {}
    exec('import os\nimport diagrams', namespace)
    exec('from diagrams import Diagram, Cluster, Edge, Node', namespace)
    exec('from diagrams.custom import Custom', namespace)
    exec('from urllib.request import urlretrieve', namespace)
    diagrams_path = os.path.dirname(diagrams.__file__)
    for provider in _PROVIDER_ORDER:
        provider_path = os.path.join(diagrams_path, provider)
        if not os.path.isdir(provider_path):
            continue
        for service_file in sorted(os.listdir(provider_path)):
            if not service_file.endswith('.py') or service_file.startswith('_'):
                continue
            try:
                exec(f'from diagrams.{provider}.{service_file[:-3]} import *', namespace)
            except Exception:
                continue
    return namespace


_BASE_NAMESPACE: Optional[dict] = None


def _new_namespace() -> dict:
    global _BASE_NAMESPACE
    if _BASE_NAMESPACE is None:
        _BASE_NAMESPACE = _build_base_namespace()
    return dict(_BASE_NAMESPACE)


def _describe_exec_error(error: Exception, code: str) -> str:
    """Point at the failing line in the submitted code; a bare exception type is not actionable."""
    detail = f'{type(error).__name__}: {error}'
    lineno = getattr(error, 'lineno', None)
    if lineno is None:
        frames = [f for f in traceback.extract_tb(error.__traceback__) if f.filename == '<string>']
        if frames:
            lineno = frames[-1].lineno
    if lineno is None:
        return f'Error generating diagram: {detail}'
    lines = code.splitlines()
    source = lines[lineno - 1].strip() if 0 < lineno <= len(lines) else ''
    return f'Error generating diagram at line {lineno}: {detail}\n    {source}'


def _save_diagram_files(output_path: str, code: str) -> Optional[str]:
    """Save the diagram code and README files."""
    try:
        # Get the directory and filename
        output_dir = os.path.dirname(output_path)
        filename_base = os.path.basename(output_path)
        
        # Save the diagram code
        code_file_path = os.path.join(output_dir, 'diagram_code.py')
        with open(code_file_path, 'w', encoding='utf-8') as f:
            f.write(f"""\"\"\"
Diagram generation code for {filename_base}
Generated by Azure Diagram MCP Server
\"\"\"

{code}
""")
        
        # Generate and save README
        return code_file_path
    except Exception as e:
        logger.error(f"Error saving diagram files: {e}")
        return None


def _find_closing_paren(code: str, start: int) -> Optional[int]:
    """Index of the ')' matching the '(' that precedes start, skipping parens inside strings."""
    depth = 1
    quote = None
    i = start
    while i < len(code):
        char = code[i]
        if quote:
            if char == '\\':
                i += 2
                continue
            if char == quote:
                quote = None
        elif char in ('"', "'"):
            quote = char
        elif char == '(':
            depth += 1
        elif char == ')':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def _rewrite_diagram_calls(code: str, output_path: str) -> str:
    """Force every `with Diagram(...)` to render to output_path without opening a viewer."""
    safe_path = output_path.replace('\\', '/')
    parts = []
    cursor = 0
    for match in re.finditer(r'with\s+Diagram\s*\(', code):
        args_start = match.end()
        if args_start < cursor:
            continue
        args_end = _find_closing_paren(code, args_start)
        if args_end is None:
            continue
        args = code[args_start:args_end].strip()
        if 'filename=' in args:
            new_args = re.sub(
                r'filename\s*=\s*[\'\"][^\'\"]*[\'\"]', f"filename=r'{safe_path}'", args
            )
        else:
            separator = ' ' if args.endswith(',') else ', '
            new_args = f'{args}{separator}' if args else ''
            new_args += f"filename=r'{safe_path}'"
        if 'show=' not in args:
            new_args += ', show=False'
        parts.append(code[cursor:args_start])
        parts.append(new_args)
        cursor = args_end
    parts.append(code[cursor:])
    return ''.join(parts)


async def generate_diagram(
    code: str,
    filename: Optional[str] = None,
    timeout: int = 90,
) -> DiagramGenerateResponse:
    """Generate a diagram from Python code using the `diagrams` package (Azure only)."""
    scan_result = await scan_python_code(code)
    if scan_result.has_errors:
        return DiagramGenerateResponse(
            status='error',
            message=f'Security issues found in the code: {scan_result.error_message}',
        )
    if filename is None:
        filename = f'diagram_{uuid.uuid4().hex[:8]}'
    # The PNG travels back with the reply, so this path is never read by the caller.
    # Fixing the directory and reducing the name to its last component keeps a crafted
    # filename from choosing where the server writes.
    output_dir = os.path.join(tempfile.gettempdir(), 'diagrams')
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, os.path.basename(filename))
    try:
        namespace = _new_namespace()
        code = _rewrite_diagram_calls(code, output_path)
        # Cross-platform timeout handling
        def timeout_handler(signum, frame):
            raise TimeoutError(f'Diagram generation timed out after {timeout} seconds')
        
        # Set up timeout mechanism (Unix systems only for signal-based timeout)
        timeout_active = False
        if platform.system() != 'Windows':
            try:
                signal.signal(signal.SIGALRM, timeout_handler)
                signal.alarm(timeout)
                timeout_active = True
            except (AttributeError, OSError):
                # Fallback for systems without SIGALRM support
                pass
        
        # Execute the diagram code
        exec(code, namespace)
        
        # Cancel the alarm if it was set
        if timeout_active:
            signal.alarm(0)
        png_path = f'{output_path}.png'
        if os.path.exists(png_path):            
            # Save diagram code and README files
            code_file_path = _save_diagram_files(output_path, code)
            
            success_message = f'Diagram generated successfully at {png_path}'
            if code_file_path:
                success_message += f'\nAdditional files created:\n- {code_file_path}'
            
            return DiagramGenerateResponse(
                status='success',
                path=png_path,
                message=success_message,
            )
        else:
            return DiagramGenerateResponse(
                status='error',
                message=(
                    f'Diagram file was not created at {png_path}. '
                    'The code must contain a `with Diagram(...):` block.'
                ),
            )
    except TimeoutError as e:
        return DiagramGenerateResponse(status='error', message=str(e))
    except Exception as e:
        return DiagramGenerateResponse(status='error', message=_describe_exec_error(e, code))

def get_diagram_examples(diagram_type: DiagramType = DiagramType.ALL) -> DiagramExampleResponse:
    """Get example code for different types of diagrams (Azure only)."""
    examples = {}
    # Azure basic example
    if diagram_type in [DiagramType.AZURE, DiagramType.ALL]:
        examples['azure_basic'] = """from diagrams import Diagram
from diagrams.azure.compute import VM
from diagrams.azure.network import LoadBalancers, VirtualNetworks
from diagrams.azure.storage import StorageAccounts

with Diagram("Basic Azure Architecture", show=False):
    # Storage
    storage = StorageAccounts("Storage Account")
    
    # Network
    vnet = VirtualNetworks("Virtual Network")
    lb = LoadBalancers("Load Balancer")
    
    # Compute
    vm = VM("Virtual Machine")
    
    # Flow
    lb >> vm >> storage
    vnet - vm"""
        
        examples['azure_comprehensive'] = """from diagrams import Diagram, Cluster
from diagrams.azure.compute import VM
from diagrams.azure.network import LoadBalancers, ApplicationGateway
from diagrams.azure.storage import StorageAccounts
from diagrams.azure.database import SQLDatabases

with Diagram("Comprehensive Azure Architecture", show=False):
    # External components
    storage = StorageAccounts("Blob Storage")
    
    # Virtual Network as main container
    with Cluster("Virtual Network (10.0.0.0/16)"):
        
        # Public subnet
        with Cluster("Public Subnet (10.0.1.0/24)"):
            lb = LoadBalancers("Load Balancer")
            app_gw = ApplicationGateway("App Gateway")
        
        # Private subnet  
        with Cluster("Private Subnet (10.0.2.0/24)"):
            vm1 = VM("Web Server 1")
            vm2 = VM("Web Server 2")
        
        # Database subnet
        with Cluster("Database Subnet (10.0.3.0/24)"):
            db = SQLDatabases("SQL Database")
    
    # Traffic flow
    app_gw >> lb
    lb >> [vm1, vm2]
    vm1 >> db
    vm2 >> db
    vm1 >> storage
    vm2 >> storage"""
    if diagram_type in [DiagramType.SEQUENCE, DiagramType.ALL]:
        examples['sequence'] = """from diagrams import Diagram
from diagrams.onprem.client import User
from diagrams.programming.flowchart import Action, Decision, InputOutput

with Diagram("User Authentication Flow", show=False):
    user = User("User")
    login = InputOutput("Login Form")
    auth = Decision("Authenticated?")
    success = Action("Access Granted")
    failure = Action("Access Denied")
    user >> login >> auth
    auth >> success
    auth >> failure"""
    if diagram_type in [DiagramType.FLOW, DiagramType.ALL]:
        examples['flow'] = """from diagrams import Diagram
from diagrams.programming.flowchart import Action, Decision, Delay, InputOutput, StartEnd

with Diagram("Order Processing Flow", show=False):
    start = StartEnd("Start")
    order = InputOutput("Order Received")
    check = Decision("In Stock?")
    process = Action("Process Order")
    wait = Delay("Backorder")
    ship = Action("Ship Order")
    end = StartEnd("End")
    start >> order >> check
    check >> process >> ship >> end
    check >> wait >> process"""
    if diagram_type in [DiagramType.CLASS, DiagramType.ALL]:
        examples['class'] = """from diagrams import Diagram
from diagrams.programming.language import Python

with Diagram("Simple Class Diagram", show=False):
    base = Python("BaseClass")
    child1 = Python("ChildClass1")
    child2 = Python("ChildClass2")
    base >> child1
    base >> child2"""
    if diagram_type in [DiagramType.K8S, DiagramType.ALL]:
        examples['k8s_exposed_pod'] = """from diagrams import Diagram
from diagrams.k8s.clusterconfig import HPA
from diagrams.k8s.compute import Deployment, Pod, ReplicaSet
from diagrams.k8s.network import Ingress, Service

with Diagram("Exposed Pod with 3 Replicas", show=False):
    net = Ingress("domain.com") >> Service("svc")
    net >> [Pod("pod1"), Pod("pod2"), Pod("pod3")] << ReplicaSet("rs") << Deployment("dp") << HPA("hpa")"""
        examples['k8s_stateful'] = """from diagrams import Diagram, Cluster
from diagrams.k8s.compute import Pod, StatefulSet
from diagrams.k8s.network import Service
from diagrams.k8s.storage import PV, PVC, StorageClass

with Diagram("Stateful Architecture", show=False):
    with Cluster("Apps"):
        svc = Service("svc")
        sts = StatefulSet("sts")
        apps = []
        for _ in range(3):
            pod = Pod("pod")
            pvc = PVC("pvc")
            pod - sts - pvc
            apps.append(svc >> pod >> pvc)
    apps << PV("pv") << StorageClass("sc")"""
    if diagram_type in [DiagramType.ONPREM, DiagramType.ALL]:
        examples['onprem_web_service'] = """from diagrams import Diagram, Cluster
from diagrams.onprem.aggregator import Fluentd
from diagrams.onprem.analytics import Spark
from diagrams.onprem.compute import Server
from diagrams.onprem.database import PostgreSQL
from diagrams.onprem.inmemory import Redis
from diagrams.onprem.monitoring import Grafana, Prometheus
from diagrams.onprem.network import Nginx
from diagrams.onprem.queue import Kafka

with Diagram("Advanced Web Service with On-Premises", show=False):
    ingress = Nginx("ingress")
    metrics = Prometheus("metric")
    metrics << Grafana("monitoring")
    with Cluster("Service Cluster"):
        grpcsvc = [Server("grpc1"), Server("grpc2"), Server("grpc3")]
    with Cluster("Sessions HA"):
        primary = Redis("session")
        primary - Redis("replica") << metrics
        grpcsvc >> primary
    with Cluster("Database HA"):
        primary = PostgreSQL("users")
        primary - PostgreSQL("replica") << metrics
        grpcsvc >> primary
    aggregator = Fluentd("logging")
    aggregator >> Kafka("stream") >> Spark("analytics")
    ingress >> grpcsvc >> aggregator"""
    if diagram_type in [DiagramType.CUSTOM, DiagramType.ALL]:
        examples['custom_storage'] = """import os
import tempfile
from urllib.request import urlretrieve

from diagrams import Diagram
from diagrams.custom import Custom

icon_url = "https://raw.githubusercontent.com/mingrammer/diagrams/master/resources/azure/storage/storage-accounts.png"
# Downloaded into the temp dir so the workspace stays clean
icon_file = os.path.join(tempfile.gettempdir(), "azure_storage.png")
urlretrieve(icon_url, icon_file)

with Diagram("Custom Azure Storage Node", show=False):
    storage = Custom("Azure Storage", icon_file)"""
    return DiagramExampleResponse(examples=examples)

def _build_icon_index() -> dict:
    """Scan the diagrams package once; importing every service module is the expensive part."""
    diagrams_path = os.path.dirname(diagrams.__file__)
    exclude_dirs = ['__pycache__', '_template']
    allowed_providers = list(_PROVIDER_ORDER)
    providers = {}
    for provider_name in os.listdir(diagrams_path):
        if provider_name not in allowed_providers:
            continue
        provider_path = os.path.join(diagrams_path, provider_name)
        if not os.path.isdir(provider_path) or provider_name in exclude_dirs:
            continue
        providers[provider_name] = {}
        for service_file in os.listdir(provider_path):
            if not service_file.endswith('.py') or service_file.startswith('_'):
                continue
            service_name = service_file[:-3]
            try:
                service_module = importlib.import_module(
                    f'diagrams.{provider_name}.{service_name}'
                )
                icons = [
                    name
                    for name, obj in inspect.getmembers(service_module)
                    if not name.startswith('_')
                    and inspect.isclass(obj)
                    and hasattr(obj, '_icon')
                ]
                if icons:
                    providers[provider_name][service_name] = sorted(icons)
            except Exception:
                continue
    return providers


_ICON_INDEX: Optional[dict] = None


def list_diagram_icons(
    provider_filter: Optional[str] = None, service_filter: Optional[str] = None
) -> DiagramIconsResponse:
    """List available Azure icons from the diagrams package, with optional filtering."""
    global _ICON_INDEX
    logger.debug(f'Filters - provider: {provider_filter}, service: {service_filter}')
    try:
        if _ICON_INDEX is None:
            _ICON_INDEX = _build_icon_index()
        providers = _ICON_INDEX
        filter_info = {}
        if provider_filter:
            needle = provider_filter.lower()
            providers = {k: v for k, v in providers.items() if needle in k.lower()}
            filter_info['provider'] = provider_filter
        if service_filter:
            needle = service_filter.lower()
            providers = {
                provider: {k: v for k, v in services.items() if needle in k.lower()}
                for provider, services in providers.items()
            }
            providers = {k: v for k, v in providers.items() if v}
            filter_info['service'] = service_filter
        return DiagramIconsResponse(
            providers=providers,
            filtered=bool(filter_info),
            filter_info=filter_info or None,
        )
    except Exception as e:
        logger.exception(f'Error in list_diagram_icons: {str(e)}')
        return DiagramIconsResponse(providers={}, filtered=False, filter_info={'error': str(e)})
